In [1]:
import pandas as pd
import codecs
import numpy as np
import glob
import os
import csv
import re

# Setting things up, importing all the necessary Python modules for the code to run!
path1 = 'C:\\Users\\kayde\\Desktop\\ENGL 301\\data_for_chapter1\\sourcefiles\\'
path2 = 'C:\\Users\\kayde\\Desktop\\measureperspective-master\\data\\'

In [3]:
stanford = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\stanford.csv')
harvard = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\inquirerbasic.csv')

allgenremeta = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\allgenremeta.csv')
final_df = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_df.csv')
final_df_tagging = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_df_tagging.csv')

final_random_df = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_random_df.csv')
final_random_df0 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_random_df0.csv')
final_random_df1 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_random_df1.csv')

final_scifi_df = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_scifi_df.csv')
final_scifi_df0 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_scifi_df0.csv')
final_scifi_df1 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_scifi_df1.csv')
final_scifi_df2 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_scifi_df2.csv')

random_fiction = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\random_fiction.csv')
chosen_sf = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\chosen_sf.csv')

seeds_df = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\seeds_df.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (63,108,109,110,176) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3,5,9,10,11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3,6,11,12,13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [4]:
master_meta = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\mastermetadata.csv')

master_final_random_df1 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\master_final_random_df1.csv')
master_final_scifi_df1 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\master_final_scifi_df1.csv')

final_random_master_df0 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_random_master_df0.csv')
final_scifi_master_df0 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_scifi_master_df0.csv')

final_random_master_df = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_random_master_df.csv')
final_scifi_master_df = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_scifi_master_df.csv')

master_final_random_df1.rename(columns = {'firstpub':'Date'}, inplace = True)

master_scifi_meta_necessary = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\master_scifi_meta_necessary.csv')
master_random_meta_necessary = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\master_random_meta_necessary.csv')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (4,5,9,10,11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
final_random_df2 = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\final_random_df2.csv')

In [6]:
# OKAY!!!

# Let's rename everything to actually make more sense, because this hideous mess is completely unreadable

final_df # this can stay
final_df_tagging # this too

random_meta0 = final_random_df.copy()
random_DTM0 = final_random_df0.copy()
random_combined_edited0 = final_random_df1.copy()
random_combined0 = final_random_df2.copy()

scifi_meta0 = final_scifi_df.copy()
scifi_DTM0 = final_scifi_df0.copy()
scifi_combined_edited0 = final_scifi_df1.copy()
scifi_combined0 = final_scifi_df2.copy()

In [7]:
random_combined1 = final_random_master_df.copy()
random_DTM1_incomplete = final_random_master_df0.copy()
random_combined_edited1 = master_final_random_df1.copy()

scifi_combined1 = final_scifi_master_df.copy()
scifi_DTM1_incomplete = final_scifi_master_df0.copy()
scifi_combined_edited1 = master_final_scifi_df1.copy()

In [9]:
scifi_combined_edited1

,Genre,Docid,Date,Title,a,aa,aaa,aaah,aaanthor,aac,...,zuzu,zuzzoo,zwei,zwergenhaus,zycki,zygote,zygotes,zz,zzt,zzz
0,0,mdp.39015039618577_0,1874,The mysterious island,1391.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,mdp.39015039618577_2,1874,The mysterious island,1050.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,mdp.39015039618577_1,1874,The mysterious island,1354.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,mdp.39015028719642_0,1877,Black diamonds,456.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,mdp.39015028719642_1,1877,Black diamonds,431.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,0,mdp.39015080836201_2,2009,Zima blue and other stories,1310.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,0,mdp.39015080836201_0,2009,Zima blue and other stories,1246.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,0,mdp.39015080836201_1,2009,Zima blue and other stories,1250.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327,0,mdp.39015080843892_0,2009,The Solaris book of new science fiction. | $c:...,1098.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,0,mdp.39015080843892_1,2009,The Solaris book of new science fiction. | $c:...,1145.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN