In [ ]:
# More testing of importing metadata/corpus data!

# This was for yet another collection of data I was trying to use, significantly larger than anything else



    # it broke my computer and I had to restart everything
        # that's when I gave up on this data
        
# please pardon the language, I was very frustrated at that point in time and I'm unable to go back and change it without waiting for a good 10-ish hours of processing

In [1]:
import pandas as pd
import codecs
import numpy as np
import glob
import os
import csv

# Setting things up
path = 'C:\\Users\\kayde\\Desktop\\ENGL 301\\data_for_chapter1\\sourcefiles\\'

In [2]:
# Testing that I'm able to import the word list for just one novel
test_df = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 301\\data_for_chapter1\\sourcefiles\\mdp.39015012361179.tsv', sep='\t', quoting=csv.QUOTE_NONE, encoding='latin1', header=0)
test_new = test_df.transpose()
test_new

,0,1,2,3,4,5,6,7,8,9,...,7810,7811,7812,7813,7814,7815,7816,7817,7818,7819
realist,amazing,compared,differently,substitute,curses,slightly,mischief,etched,sahib,horsemen,...,bahadur,bags,rinsing,monument,departing,beats,waterfalls,maps,pranced,empty
1,1,2,1,8,1,7,5,1,15,1,...,4,6,1,1,1,3,1,1,1,6

In [106]:
all_meta = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 343\\allgenremeta.csv')
all_meta

,docid,firstpub,date,birthdate,recept,tags,enumcron,nationality,gender,author,title
0,njp.32101074032044,1700,1700,1700,NaN,bio,<blank>,NaN,NaN,Epictetus.,Epictetus his morals
1,mdp.39015047759454,1700,1700,1700,NaN,poe,NaN,NaN,NaN,"Brome, Charles,",To the memory of Mr. Dryden
2,mdp.39015084592289,1700,1700,1700,NaN,poe,NaN,NaN,NaN,NaN,Luctus britannici
3,mdp.39015086635185,1700,1700,1700,NaN,poe,NaN,NaN,NaN,NaN,A new session of the poets
4,uc1.32106001529731,1700,1700,1700,NaN,poe,NaN,NaN,NaN,NaN,The Oxford book of Greek verse in translation
...,...,...,...,...,...,...,...,...,...,...,...
5742,inu.30000067206494,1999,1999,1964,NaN,poe,NaN,NaN,NaN,"Reimer, Lotte.",Wind and wild magic
5743,inu.30000079522466,1999,1999,1964,NaN,poe,NaN,NaN,NaN,"Mbanuzue, Benedicta.",Sunrise in Africa
5744,inu.30000046089342,1999,1999,1964,NaN,poe,NaN,NaN,NaN,"Uba, Becky.",White date
5745,inu.30000046089359,1999,1999,1964,NaN,poe,NaN,NaN,NaN,"Babatunde, Sola Timothy.",The valley of vision
5746,mdp.39015063163003,1999,1999,1964,NaN,poe,NaN,NaN,NaN,"Masso, Charles A.",Mystical woman in verse

In [3]:
hathi_meta = pd.read_csv('C:\\Users\\kayde\\Desktop\\ENGL 301\\hathigenremeta.csv')
# Okay, I messed up here, this is the wrong csv!!! I'll instead use the on above, that is for all the data files
hathi_meta

,docid,firstpub,date,birthdate,recept,tags,enumcron,nationality,gender,author,title
0,njp.32101074032044,1700,1700,1700,NaN,bio,<blank>,NaN,NaN,Epictetus.,Epictetus his morals
1,njp.32101067675031,1701,1701,1701,NaN,bio,<blank>,NaN,NaN,"Le Clerc, Jean,","The lives of the primitive fathers, viz, Cleme..."
2,mdp.39015030832490,1701,1701,1701,NaN,bio,<blank>,NaN,NaN,"Blomberg, Karl Johann von,",An account of Livonia
3,uc2.ark+=13960=t0js9xc1p,1702,1702,1702,NaN,fic,NaN,NaN,NaN,NaN,"The infernal wanderer; or, The Devil ranging u..."
4,mdp.39015014822228,1702,1702,1702,NaN,bio,<blank>,NaN,NaN,"Guthry, Henry,",Memoirs of Henry Guthry
...,...,...,...,...,...,...,...,...,...,...,...
3569,mdp.39015050288813,1999,1999,1942,NaN,fic,NaN,NaN,NaN,"Cohen, Matt,",Elizabeth and after
3570,mdp.39015047452530,1999,1999,1964,NaN,fic,NaN,NaN,NaN,"Sheen, Anitra Peebles.",Things unspoken
3571,mdp.39015047492957,1999,1999,1964,NaN,fic,NaN,NaN,NaN,"Alderman, Annabel.",Family man
3572,mdp.49015002517838,1999,1999,1966,NaN,fic,NaN,NaN,NaN,"Hartman, Keith,","The gumshoe, the witch, and the virtual corpse"
3573,uc1.32106014838277,1999,1999,1931,NaN,fic,NaN,NaN,NaN,"Raphael, Frederic,",Coast to coast

In [4]:
hathi_dfs_list = []

for index, row in hathi_meta.iterrows():
    filepath = path + row['docid'] + '.tsv'
    file_df = pd.read_csv(filepath, sep='\t', quoting=csv.QUOTE_NONE, encoding='latin1')
    flipped_df = file_df.transpose()
    flipped_df = flipped_df.reset_index(level=0)
    flipped_df.columns = flipped_df.iloc[0]
    flipped_df = flipped_df.drop([0])
    flipped_df = flipped_df.reset_index()
    

    hathi_dfs_list.append(flipped_df)
hathi_dfs_list

[0  index      ,   and   the    to    of     .  that     a    is  ... "*" "'  \
 0      1  14743  8014  6768  4975  4973  4139  2926  2514  2451  ...   1  1

 0 "", """ "" !?''"' !? !. !, NaN
 0   1   1  1      1  1  1  1   1

 [1 rows x 11195 columns],
 0  level_0     ,   the    of     .    to  that   and    he    in  ... "; "*  \
 0        1  7985  5216  3595  2977  2488  2333  2032  1603  1470  ...  1  1

 0 !{ !?, !:. !: !- !,, !" NaN
 0  1   1   1  1  1   1  1   1

 [1 rows x 10468 columns],
 0  index     ,   the    of   and     .    to    in     a    ;  ... "", ""'  \
 0      1  7042  4001  2600  2441  2071  1728  1181  1016  856  ...   1   1

 0 !^; !? !; !: !/, !);, !)' !'
 0   1  1  1  1   1    1   1  1

 [1 rows x 16862 columns],
 0  index    ,  the   of    a  and   to    i    .   in  ...  * )', (./. ('  \
 0      1  714  381  260  252  195  186  156  144  117  ...  1   1    1  1

 0 'â  '. ', ", !: !)
 0    1  1  1  1  1  1

 [1 rows x 2588 columns],
 0  index     ,   the    to   and    of     .  that    in   his  ... $.t#te  \
 0      1  6590  5603  2872  2836  2696  2018  1398  1223  1040  ...      1

 0 #.. "â¢ "?. ".. "'"* """' !? !.] NaN
 0   1    1   1   1    1    1  1   1   1

 [1 rows x 8766 columns],
 0  level_0      ,    the      .    of   and    to     '     a     ;  ... ""':  \
 0        1  19540  12908  12665  8186  7086  6093  4978  4819  3838  ...    1

 0 ""'"; ""'"- ""'"' """: """' !; !.: !' !"
 0     1     1     1    1    1  1   1  1  1

 [1 rows x 37452 columns],
 0  index     ,   the    of   and    to     .    in  that     a  ... ".". ".  \
 0      1  6446  5390  3768  3177  3076  2351  1702  1506  1467  ...    1  1

 0 "-' "*"'/ "* ") "', ""(!' "!' !]
 0   1     1  1  1   1     1   1  1

 [1 rows x 9921 columns],
 0  index      ,   the    of   and     .    to    in     i  that  ... #^/tf  \
 0      1  11719  6369  4622  4052  3770  3718  2386  2117  2042  ...     1

 0 "*~ ") "'**/>â¢ "'*' "' "! !. !' NaN
 0   1  1         1    1  1  1  1  1   1

 [1 rows x 13971 columns],
 0  index      ,    the    to   and    of     i  that    in    he  ... !: !.<.  \
 0      1  22394  10365  8684  8461  7472  4490  4434  4156  4039  ...  1    1

 0 !.. !- !) !'; !'. !', !' !!:
 0   1  1  1   1   1   1  1   1

 [1 rows x 24310 columns],
 0  index     ,    to   the    of   and  that    .    a    i  ... %kf %^ $ewi  \
 0      1  4438  1633  1552  1208  1141  1003  873  730  605  ...   1  1    1

 0 $& "â> "..â¢'â¢ "- ", "* !,
 0  1     1          1  1  1  1  1

 [1 rows x 7465 columns],
 0  index      ,   the   and    to    of     .  that   his    he  ...  \
 0      1  14543  9484  4529  4188  3895  3377  2748  2379  2350  ...

 0 !.-..â¢â¢.; !.': !-â¢â¢. !- !,, !) !'; !'' !" !!
 0             1    1         1  1   1  1   1   1  1  1

 [1 rows x 19227 columns],
 0  index    .    ,    '    a  the    -    ;    i  and  ... "( "') "". ""* ""'  \
 0      1  785  628  600  301  298  297  244  214  180  ...  1   1   1   1   1

 0 """ "" !? !$*: !"
 0   1  1  1    1  1

 [1 rows x 3536 columns],
 0  index     ,   the    to    of   and     .  that    in    it  ... "- "* ")  \
 0      1  8461  4672  3784  3345  3261  2383  1855  1836  1778  ...  1  1  1

 0 "'...-. "' "% "" !^ !, NaN
 0       1  1  1  1  1  1   1

 [1 rows x 6621 columns],
 0  index     ,   the    to    of   and     .  that    in   was  ... """ "! !?  \
 0      1  8933  6700  3328  3320  2985  2770  1504  1382  1186  ...   1  1  1

 0 !; !.'â¢â¢'â¢â¢.*Â« !- !))<&â¢/& !) !' !"
 0  1                    1  1          1  1  1  1

 [1 rows x 12685 columns],
 0  index     ,   the    of     .   and    to    he   his    in  ... ': '.....  \
 0      1  5014  3851  3213  1792  1785  1547  1527  1208  1182  ...  1      1

 0 '.. '*â¢ &? $6 "> ".â  "' NaN
 0   1     1  1  1  1     1  1   1

 [1 rows x 7519 columns],
 0  index    the      ,    of   and    to     .   his    he    in  ... "}** "^  \
 0      1  14884  14770  6808  6123  6085  5002  3351  3185  2870  ...    1  1

 0 "? "; "** "'.."'/ !: !) !' !!
 0  1  1   1       1  1  1  1  1

 [1 rows x 15999 columns],
 0  index      ,    the    of   and    to     .   his    he    in  ... "â   \
 0      1  12630  10751  5560  5153  4880  4217  2684  2329  2278  ...    1

 0 "â¢ ">? "; ". "" !. !), !'. !"
 0    1   1  1  1  1  1   1   1  1

 [1 rows x 14403 columns],
 0  index     ,   the     .    of   and    to    in     '  that  ... "". ""''  \
 0      1  6890  3818  3474  2926  2878  2200  1544  1513  1297  ...   1    1

 0 ""' """"' """ !: !., !. !), !)
 0   1     1   1  1   1  1   1  1

 [1 rows x 11983 columns],
 0  index     ,  the  and   to    .   of  his    a   he  ... '- ', '* ''. '''  \
 0      1  1278  551  497  397  358  294  250  218  209  ...  1  1  1   1   1

 0 '' '"/?'â¢? '"'  % "?
 0  1         1   1  1  1

 [1 rows x 2818 columns],
 0  index     ,   the     .    to   of  you  and    i    a  ... $. "Â« ".-. "*  \
 0      1  1800  1167  1160  1019  885  725  656  639  504  ...  1   1    1  1

 0 "' !; !.'. !, !) NaN
 0  1  1    1  1  1   1

 [1 rows x 5253 columns],
 0  index     ,   the    of   and    to  that    in   his     .  ... %\ $lf $.  \
 0      1  6015  3315  2541  2372  1697  1210  1194  1023  1011  ...  1   1  1

 0  # ": ". "* "'. "'- "''"'
 0  1  1  1  1   1   1     1

 [1 rows x 7328 columns],
 0  index      ,   the    of   and     .    to    in  that     a  ... "! !~.  \
 0      1  15070  9252  8119  5578  4996  4422  3605  3425  2658  ...  1   1

 0 !} !, !* !'â¢â¢"-' !'' !&?Â£.; !"â¢ !!
 0  1  1  1           1   1       1     1  1

 [1 rows x 20643 columns],
 0  index     ,   the   and    to    of     .  his   in   he  ... ".* ". ",  \
 0      1  4255  2494  1762  1437  1434  1062  781  753  625  ...   1  1  1

 0 "*""' "* ""' "" "!, !; !.
 0     1  1   1  1   1  1  1

 [1 rows x 7337 columns],
 0  index      ,   the    of   and     .    to    in     a  that  ... ""'? ""&  \
 0      1  12648  8723  7005  5585  5084  4319  2962  2448  2395  ...    1   1

 0 """'â¢ """ !â¢/! !Â« !* !' !"*â"*/ !"
 0       1   1      1   1  1  1         1  1

 [1 rows x 19357 columns],
 0  index      ,   the    to    of     .   and     i     a   you  ... %btf  \
 0      1  10968  5263  4615  3766  3273  2893  2710  2363  2085  ...    1

 0 $ugucs #Â£* #blige "! !> !: !) !' NaN
 0      1    1      1  1  1  1  1  1   1

 [1 rows x 9535 columns],
 0  index      ,   the    to   and     .    of     a    he     i  ... $traw  \
 0      1  19738  7880  7552  6953  5711  5378  4050  3978  3637  ...     1

 0 $ffedation "^ "; ". !? !< !; !:, !"
 0          1  1  1  1  1  1  1   1  1

 [1 rows x 15315 columns],
 0  index      ,   the    to   and     i    of     .     a    my  ... '] ':  \
 0      1  11400  5352  4887  4769  4363  3656  3000  2791  2249  ...  1  1

 0 '.?  & $â¢ $, ", "' !; !:
 0   1  1    1  1  1  1  1  1

 [1 rows x 10183 columns],
 0  index     ,   the    to    of     .   and   he    a  his  ... %tke  \
 0      1  3997  3401  1926  1500  1499  1401  927  911  749  ...    1

 0 %?di>la% %, %)eath $eak ##dvr "? "* "', !.
 0        1  1      1    1     1  1  1   1  1

 [1 rows x 6448 columns],
 0  index     ,   the    of     .    to   and    he    a   in  ... '%%$  \
 0      1  3239  2693  2115  1971  1447  1225  1023  935  907  ...    1

 0 %kftttf %iven %'  # ": !-? !- !! NaN
 0       1     1  1  1  1   1  1  1   1

 [1 rows x 6388 columns],
 0  level_0      ,    the     of      .    and     to    in  that     a  ...  \
 0        1  32292  26601  16780  14987  12455  10378  7370  6223  5590  ...

 0 !?"^' !/> !/)Â«/; !/)Â«('>Â«Â»<Â«, !."' !-^ !'. !" !!> !!
 0     1   1       1                1    1   1   1  1   1  1

 [1 rows x 52477 columns],
 0  index      ,    the     of   and     .    to    in  that    he  ... !,.,  \
 0      1  24925  17949  11828  9311  8203  7771  5511  4755  4085  ...    1

 0 !*â¢ !)â¢ !) !'>â¢'â¢ !': !"' !""' !!, !!!
 0     1     1  1          1   1   1    1   1   1

 [1 rows x 41645 columns],
 0  level_0      ,    the     of      .   and    to    in  that    he  ...  \
 0        1  22987  19860  12557  11493  8909  7126  5786  5521  4241  ...

 0 !<Â»- !: !.: !./.Â«, !." !. !'/><Â»? !''' !' !!
 0     1  1   1       1   1  1        1    1  1  1

 [1 rows x 49390 columns],
 0  index     ,   the    to    of   and   her     a    he     .  ... #ot "Â£/'  \
 0      1  6371  3323  2508  2130  1754  1499  1380  1291  1190  ...   1     1

 0 "?) "//, ". ", !. !- !, !!
 0   1    1  1  1  1  1  1  1

 [1 rows x 8768 columns],
 0  index     ,   the    to    of   and     .   her     a  that  ...  \
 0      1  6063  3492  2758  2594  1848  1734  1530  1405  1172  ...

 0 #rcumftances  # "Â«; "?) ") !â  !. !, !) !(
 0            1  1    1   1  1    1  1  1  1  1

 [1 rows x 8726 columns],
 0  index     ,   the    of  and    .   to    i   in |arabic1digit|  ... "'}  \
 0      1  2315  1873  1184  983  972  881  592  549            506  ...   1

 0 "''â¢â¢ "''â¢), "' ""Â» !;,, !; !, !''â¢â¢' !'
 0         1        1  1    1    1  1  1          1  1

 [1 rows x 5328 columns],
 0  index    ,  the   of  and    .    a  his   he   to  ... .* .'â â  -,  \
 0      1  491  325  195  182  149  141  127  118  115  ...  1        1  1

 0 (Â») (?) (" 'â â ' #~7 "" !â â â â
 0    1   1  1        1   1  1             1

 [1 rows x 1724 columns],
 0  index     ,   the    to     .     i    of   and  that     '  ... !'â¢  \
 0      1  5146  2737  2282  2201  1864  1754  1501  1163  1136  ...     1

 0 !'Â»' !$ !">.*"Â». !")Â» !"'Â» !"': !" !!!' !!
 0     1  1         1     1     1    1  1    1  1

 [1 rows x 12331 columns],
 0  level_0    the      ,    of    to     .   and     '  that    in  ...  \
 0        1  12832  11735  7191  5309  4852  4635  3546  2978  2273  ...

 0 !<;;,. !<'/Â£Â«Â« !: !/. !.. !-â¢: !-. !'â¢-â¢ !%. !!,
 0      1          1  1   1   1      1   1         1   1   1

 [1 rows x 23532 columns],
 0  index      ,    the   and    of    to     .     a  that    in  ... "'â¢  \
 0      1  15117  10852  7412  6758  5269  3494  3016  2980  2896  ...     1

 0 "'" "") ""' """ !? !: !, !"' !"
 0   1   1   1   1  1  1  1   1  1

 [1 rows x 16890 columns],
 0  level_0      ,    the    of   and    to     .    in   his  that  ... ""<"*  \
 0        1  14405  11059  8193  5345  4796  3923  3243  2703  2509  ...     1

 0 ""-^ ""'. """*' """" """ !â¢ !: !*â¢Â»â¢'â¢â  !$'
 0    1    1     1    1   1    1  1                 1   1

 [1 rows x 16892 columns],
 0  index     ,     .   the    to   and   he  his    :    ;  ... "!' "! !â¬  \
 0      1  4558  2182  1489  1094  1016  856  815  718  693  ...   1  1    1

 0 !â¢.â¢' !â¢' !Â»" !Â»! !; !.; !-Â»
 0         1     1    1    1  1   1    1

 [1 rows x 6751 columns],
 0  index    ,  the   of  and   to    . her  in   a  ...  / .: .. 'â  '. ',  \
 0      1  364  204  185  154  133  118  93  78  71  ...  1  1  1    1  1  1

 0 '*. %)ivine  # !'
 0   1       1  1  1

 [1 rows x 1317 columns],
 0  index     ,   the   and    of     a    to     .    i   in  ... $, "â¢  \
 0      1  5384  2442  1663  1388  1377  1364  1093  973  728  ...  1    1

 0 "-Â» ", "* "'.â¢ ""'' !.-. !) NaN
 0    1  1  1      1    1    1  1   1

 [1 rows x 8617 columns],
 0  index     ,   the    to   and    of    he    a    .  his  ... &ttd %pri  \
 0      1  3766  1724  1299  1147  1116  1104  933  864  821  ...    1    1

 0 %jani %. $. $- $, "'^; "' !,
 0     1  1  1  1  1    1  1  1

 [1 rows x 6727 columns],
 0  index     ,   the    of    to   and     .    in  that   his  ... ""'  \
 0      1  9595  8584  5499  3806  3564  2583  2160  2159  1842  ...   1

 0 """*Â£. """"' """ !> !: !.â¢ !. !, !$<,
 0       1     1   1  1  1     1  1  1    1

 [1 rows x 12971 columns],
 0  level_0      ,    the     of   and    to     .     a    in  that  ... !{  \
 0        1  19644  14769  10038  8419  6064  4827  4246  3714  2855  ...  1

 0 !;! !.. !.'- !.' !. !- !( !#Â£â¢% !!
 0   1   1    1   1  1  1  1        1  1

 [1 rows x 23071 columns],
 0  level_0     ,   the    of     .   and    to    in    a   be  ... "^ "> "..  \
 0        1  5525  4651  3018  2307  1780  1580  1179  732  714  ...  1  1   1

 0 ".'; "*' "*% ""â¢ !? !) !'
 0    1   1   1     1  1  1  1

 [1 rows x 11694 columns],
 0  index     ,  the   of  and   to    .  his   in that  ... *!â¢'â¢ ):  \
 0      1  1165  998  552  465  433  353  301  261  204  ...         1  1

 0 '.'*' ', '( '"  $ ", "' !}
 0     1  1  1  1  1  1  1  1

 [1 rows x 3224 columns],
 0  index      ,   the    of    to   and     .  that    in   his  ... ""-  \
 0      1  12365  9559  5448  4735  4529  3089  2636  2607  2219  ...   1

 0 """.' """ !; !."., !. !,, !' !&& NaN
 0     1   1  1     1  1   1  1   1   1

 [1 rows x 11279 columns],
 0  level_0     ,   the     .   and    of    to     a   in that  ...  \
 0        1  4561  2137  1442  1411  1294  1142  1069  647  554  ...

 0 "â â â  ".. "- ", "* "' """ "" !â  !,
 0          1   1  1  1  1  1   1  1    1  1

 [1 rows x 7873 columns],
 0  index     ,   the     .     "   to  and   of    a    i  ... absent  \
 0      1  2013  1747  1357  1050  752  665  553  454  423  ...      1

 0 abridged above abomination ability abandoned abandon ., .' ''
 0        1     1           1       1         1       1  1  1  1

 [1 rows x 3475 columns],
 0  index     ,   the     .     "   and    to   of    a    i  ... abode  \
 0      1  3115  2464  1792  1275  1151  1092  691  653  595  ...     1

 0 abandonment abandoned  \ .'"  * ''  # "- "'
 0           1         1  1   1  1  1  1  1  1

 [1 rows x 4254 columns],
 0  level_0     ,   the   to  her   of  and    a  was    ;  ... '- ',  \
 0        1  2095  1074  966  772  758  671  478  475  460  ...  1  1

 0 &?vaidrivella %po<x'$uygmdy %isit  % "..Â«; "'' !- !,
 0             1             1     1  1      1   1  1  1

 [1 rows x 4214 columns],
 0  index    ,  the    .   of  and   to   i  in  my  ... '( '' '"  & $hiÂ¿h  $  \
 0      1  428  241  220  198  156  144  94  83  81  ...  1  1  1  1      1  1

 0 ";. "- "'- !!
 0   1  1   1  1

 [1 rows x 1945 columns],
 0  index     ,   the    of    to   and     .  that     '    in  ... "*  \
 0      1  9302  6374  3509  3027  2718  2376  1941  1883  1635  ...  1

 0 "(%),... ""' "" "! !âºÂ»â¢.â * !Â«-.Â»*. !> !. !-,,
 0        1   1  1  1              1         1  1  1    1

 [1 rows x 13178 columns],
 0  index      ,   the   and    to    of    in     .     ;    he  ... %)  $  \
 0      1  14593  7540  6660  4605  4480  3298  2859  2481  2133  ...  1  1

 0 #tijeÂ£hdal  # "â¢ "] "; "). "( NaN
 0           1  1    1  1  1   1  1   1

 [1 rows x 8822 columns],
 0  index     ,   the    to    of   and     .  that   his    in  ... "^ "? ":  \
 0      1  4536  4245  2157  2078  1915  1808  1270  1172  1115  ...  1  1  1

 0 ". ", "'- "'' "'" "' !-
 0  1  1   1   1   1  1  1

 [1 rows x 7634 columns],
 0  index     ,   the    of   to  and    .   in  his that  ... $jttÂ«efs "â¢  \
 0      1  2636  1429  1050  805  680  592  536  456  404  ...         1    1

 0 ">. "-'â¢-.-. ", "'.'"â¢â¢â¢â¢ "' !, !) NaN
 0   1          1  1                 1  1  1  1   1

 [1 rows x 5253 columns],
 0  index     ,   the    of    to   and     .     '  that    in  ... !{'. !:,  \
 0      1  8496  6174  3880  3069  3055  2598  1717  1710  1700  ...    1   1

 0 !: !..: !- !) !'!; !' !",, !!
 0  1    1  1  1    1  1    1  1

 [1 rows x 13383 columns],
 0  index      ,    the    of   and     .    to    in     a  that  ... "- "';  \
 0      1  14189  10492  6670  6295  5024  4334  3152  2407  2056  ...  1   1

 0 "' "& "! !? !; !: !.] !.
 0  1  1  1  1  1  1   1  1

 [1 rows x 16656 columns],
 0  index      ,   the    of   and     .    to    in     a  that  ... "} "] ">  \
 0      1  13556  9040  5688  5553  4369  3811  2653  2256  2062  ...  1  1  1

 0 ".: "' !â¢Â«â¢ !} !^ !;; NaN
 0   1  1         1  1  1   1   1

 [1 rows x 20587 columns],
 0  index     ,   the   and    to     .    of    he   her     a  ... ".*.....  \
 0      1  4290  2439  2014  1978  1759  1574  1481  1324  1237  ...        1

 0 "*. "* ") "( "', !..; !... !.'; !,.
 0   1  1  1  1   1    1    1    1   1

 [1 rows x 7238 columns],
 0  index     ,   the    of   to    .  and  his   in that  ... $&cej[fity  \
 0      1  2235  1720  1282  860  807  800  552  412  370  ...          1

 0 #swÂ£yifc "; ".; ".. ", "* "'.' "''. !,
 0         1  1   1   1  1  1    1    1  1

 [1 rows x 5498 columns],
 0  level_0      ,    the    of     .   and    to  that     a    in  ...  \
 0        1  10988  10234  6821  4081  3892  3447  3000  2690  2568  ...

 0 !â¢â '.â â¢.,; !â¢ !Â»: !?: !; !.: !..â¢!;;, !.... !'; NaN
 0                  1    1    1   1  1   1          1     1   1   1

 [1 rows x 15540 columns],
 0  index     ,  the   to    i    .   of  and   my    a  ... ,,, ,) ,! ). )',  \
 0      1  1145  470  459  369  293  282  278  258  257  ...   1  1  1  1   1

 0 )' $(,  # ") !:
 0  1   1  1  1  1

 [1 rows x 2334 columns],
 0  level_0      ,   the    of   and     .    to    in     a   his  ... !â¢:  \
 0        1  11308  7445  6171  5355  5016  4533  2658  2117  1938  ...     1

 0 !}' !} !^ !< !.'; !-; !, !)(?. !)
 0   1  1  1  1    1   1  1     1  1

 [1 rows x 16200 columns],
 0  index     ,   the    to    of   and     i     .     a   you  ... "^^^^ "^  \
 0      1  8745  3873  3769  2614  2361  2340  2239  1736  1625  ...     1  1

 0 "; ". "*â¢ ") "' !â  !â¢ !,!
 0  1  1     1  1  1    1    1   1

 [1 rows x 10032 columns],
 0  index      ,   the     i   and    to    of     a    my   was  ...  \
 0      1  11901  5688  4521  4501  4108  3370  2208  2067  1900  ...

 0 #ft$?wards #bouÂ£fijfjcy "} "^. "; "' !<*> !; !, NaN
 0          1             1  1   1  1  1    1  1  1   1

 [1 rows x 11965 columns],
 0  index     ,   the    to   and    of    i    .    a that  ... '.'.<$ '."  \
 0      1  2873  1366  1093  1031  1005  739  639  617  597  ...      1   1

 0 '-â¢â¢' &Â£. $*.] "â¢. "' !.. !. !*
 0         1    1    1     1  1   1  1  1

 [1 rows x 4529 columns],
 0  level_0     ,   the     .    of     "   and   to that   in  ... "'*' "''  \
 0        1  2952  1728  1716  1497  1100  1018  950  717  702  ...    1   1

 0 ""-' """*"* """" """ ""!!; !Â«'&' !.â¢ NaN
 0    1      1    1   1     1      1     1   1

 [1 rows x 6914 columns],
 0  index     ,   the    of     .   and    to     a    in  that  ... "'[ "''  \
 0      1  7787  6286  3901  3104  2587  1987  1772  1758  1243  ...   1   1

 0 ""â¢- ""' !â¢ !: !.Â«, !...Â» !. !!
 0      1   1    1  1     1      1  1  1

 [1 rows x 12114 columns],
 0  index     ,     .   the    of     a   and     ;    in |romannumeral|  ...  \
 0      1  6717  5471  4812  3001  2225  1788  1681  1663           1335  ...

 0 ") "'â¢' "'' "&*&*&*&*Â£, """"â â "" "! !â¢ !Â», !:; !".
 0  1      1   1            1            1  1    1    1   1   1

 [1 rows x 10791 columns],
 0  index     ,   the    of   and     .    to    in that they  ... ") "'./'  \
 0      1  5277  4015  2692  2157  1474  1301  1195  917  702  ...  1     1

 0 "', !? !; !: !,, !*â¢ !'.,; !'.
 0   1  1  1  1   1     1     1   1

 [1 rows x 8010 columns],
 0  index     ,  the   to   of  and    .    '  his    a  ... '* '( '', '"*  \
 0      1  1378  671  482  433  417  356  273  247  240  ...  1  1   1   1

 0 '!.. %/ng ".'...â¢ "* !, NaN
 0    1    1         1  1  1   1

 [1 rows x 3630 columns],
 0  level_0     ,     .   the    of   and     a    to    in   his  ... !: !...  \
 0        1  6442  4749  4326  3188  2330  1682  1671  1612  1388  ...  1    1

 0 !., !.) !.' !-*' !, !) !' !"
 0   1   1   1    1  1  1  1  1

 [1 rows x 12861 columns],
 0  index      ,   the   and    to    of    we     .     a     ;  ...  1  \
 0      1  11193  5257  4255  3810  3304  2977  2084  2053  1931  ...  1

 0 /esopâs  / -~ -. -, ); ): (; "â
 0         1  1  1  1  1  1  1  1    1


In [5]:
type(hathi_dfs_list)

list

In [6]:
large_eighteenth_df = pd.concat(hathi_dfs_list, axis=0, ignore_index=True)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [7]:
test_hathi = hathi_meta.sample(n=10)
smaller_dfs = []
for index, row in test_hathi.iterrows():
    filepath = path + row['docid'] + '.tsv'
    file_df = pd.read_csv(filepath, sep='\t', quoting=csv.QUOTE_NONE, encoding='latin1')
    flipped_df = file_df.transpose()
    flipped_df = flipped_df.reset_index(level=0)
    flipped_df.columns = flipped_df.iloc[0]
    flipped_df = flipped_df.drop([0])
    

    smaller_dfs.append(flipped_df)
    
smaller_dfs

[0     ,     .   the    to   and     "    of    he  that   was  ... .â¢//. --  \
 1  6596  5741  4398  3214  2692  2458  2278  1902  1750  1523  ...       1  1

 0 +*Â»Â« ),  ( 'â  'â¢' '* "* ""'
 1      1  1  1    1     1  1  1   1

 [1 rows x 7227 columns],
 0 =<wv  : \|Â§ theyâre amazing them trouble relief *1 own  ... fast  \
 1    1  5    1         1       1    9       1      1  1   1  ...    1

 0 1ï¬'ing jpn bradï¬eld giant fair mice live day let
 1        1   1          2     3    1    3    1   1   1

 [1 rows x 679 columns],
 0     ,   the    of    to    .  and    a  his   he   in  ... ''' '' '%, %gty  \
 1  3373  1591  1218  1032  950  765  744  723  554  517  ...   1  1   1    1

 0 %$  %  $ #iook !â¢ !!
 1  1  1  1     1    1  1

 [1 rows x 5047 columns],
 0 recognising wounds commitment german substitute reverses heath hal littered  \
 1           3      2          1      3          2        3     2   1        1

 0 undertaking  ... licensed â¢oÂ«th monument fenced obstructions vv 1.50  \
 1           4  ...        1        1        2      2            1  1    1

 0 treachery added corpus
 1         1    39      1

 [1 rows x 15902 columns],
 0     ,   the     .   and    of    to     i    my   was     a  ... "" !Â«<:,  \
 1  9120  5261  3450  3118  2893  2854  2536  1795  1674  1642  ...  1      1

 0 !\, !? !:; !.. !- !* !!^ !!;
 1   1  1   1   1  1  1   1   1

 [1 rows x 14874 columns],
 0     ,   the    of   and    to     .   his    in    he   was  ... $mpi're  \
 1  9168  6766  4075  2811  2637  1964  1616  1577  1557  1322  ...       1

 0 $aviour #,  # ". "'* "' !}', !, !!!
 1       1  1  1  1   1  1    1  1   1

 [1 rows x 9351 columns],
 0     ,   the   â   and    of     .    to     a     i   in  ... ',,, '*-'  \
 1  4675  2501  1700  1569  1489  1334  1256  1209  1005  929  ...    1    1

 0  % $i>attcfy "â¢ "? ", !-< !* !'*
 1  1         1    1  1  1   1  1   1

 [1 rows x 7244 columns],
 0 crouch casuarinas mike boring commitment differently houses tanned  \
 1      1          3    1      6          3           6      9      1

 0 perimeter littered  ... tidily fenced weekly lime jul maps added breasts  \
 1         1        2  ...      1      1      3    2   1    4     1       2

 0 nefertiti turquoise
 1         1         3

 [1 rows x 9378 columns],
 0 realist matured mieux bar differently substitute tanned dipping unfair  \
 1       1       1     1   1           1          1      1       1      1

 0 mischief  ... never trapeze perimeters rehung origin eyes elsewhere added  \
 1        1  ...    65       1          1      1      2   32         2    19

 0 empty hastened
 1     6        1

 [1 rows x 6585 columns],
 0     ,   the    of   to  and   in    .    a  his that  ...  - *Â« *?? )" %ht  \
 1  2231  1823  1428  937  865  569  567  427  347  321  ...  1   1   1  1   1

 0 $* ######â¢#Â» ###########  # "*
 1  1            1           1  1  1

 [1 rows x 4573 columns]]

In [8]:
smaller_dfs = []
i = 1
for index, row in test_hathi.iterrows():
    filepath = path + row['docid'] + '.tsv'
    file_df = pd.read_csv(filepath, sep='\t', quoting=csv.QUOTE_NONE, encoding='latin1')
    flipped_df = file_df.transpose()
    flipped_df = flipped_df.reset_index(level=0)
    flipped_df.columns = flipped_df.iloc[0]
    flipped_df = flipped_df.drop([0])
    

    smaller_dfs.append(flipped_df)

In [9]:
large_df = pd.concat(smaller_dfs, axis=0, ignore_index=True)
large_df

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [11]:
hathi_dfs_list[0].columns.duplicated().any()

True

In [17]:
duped_dfs_list = []
for df in hathi_dfs_list:
    dupe_df = df.loc[:,~df.columns.duplicated()]
    duped_dfs_list.append(dupe_df)

In [18]:
duped_dfs_list[0].columns.duplicated().any()

False

In [20]:
partial_list = duped_dfs_list[0:100]

In [43]:
partial_df = pd.concat(partial_list, axis=0, ignore_index=True)

In [23]:
import re

In [51]:
partial_df

,index,",",and,the,to,of,.,that,a,is,...,$\.,$(Â«,$$â¢,$$.,#qrty,"""â¢Â»",""".â¢*'""â¢*","""'Â»","""'*â¢","!>â¢Â£Â»,"
0,1,14743,8014,6768,4975,4973,4139,2926,2514,2451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,7985,2032,5216,2488,3595,2977,2333,1175,725,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,7042,2441,4001,1728,2600,2071,835,1016,416,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,714,195,381,186,260,144,73,252,23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,6590,2836,5603,2872,2696,2018,1398,781,21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7,12477,4098,9380,3166,6364,7070,2551,2648,1270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,8,11055,2989,6848,2703,4443,6820,2592,2486,929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,5,11392,3220,9318,3288,6199,6783,2896,2724,1058,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,8,10664,3549,8563,3072,5765,6489,2919,2915,1284,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,10,13479,4176,9853,3832,6381,7189,3212,2639,1107,...,1,1,1,1,1,1,1,1,1,1

In [74]:
fucked_up_df = partial_df.copy()

In [75]:
fucked_up_df.columns = [str(i) for i in fucked_up_df.columns.values.tolist()]

In [83]:
fucked_up_df.columns = [re.sub(r'[^A-Za-z]', 'dropme', c) for c in fucked_up_df.columns.values.tolist()]
# Cleaning it all, then removing unnecessary columns

In [84]:
fucked_up_df = fucked_up_df[fucked_up_df.columns.drop(list(fucked_up_df.filter(regex='dropme')))]
# Putting it all together!

In [85]:
fucked_up_df

,index,and,the,to,of,that,a,is,in,it,...,abderitaram,abderitanus,abderi,abderas,abder,abbreviation,abarbanslf,abalita,aafl,aaf
0,1,8014,6768,4975,4973,2926,2514,2451,2261,2031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,2032,5216,2488,3595,2333,1175,725,1470,883,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2441,4001,1728,2600,835,1016,416,1181,411,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,195,381,186,260,73,252,23,117,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2836,5603,2872,2696,1398,781,21,1223,573,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,7,4098,9380,3166,6364,2551,2648,1270,3140,1302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,8,2989,6848,2703,4443,2592,2486,929,2270,1122,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,5,3220,9318,3288,6199,2896,2724,1058,2681,1262,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,8,3549,8563,3072,5765,2919,2915,1284,2627,1439,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,10,4176,9853,3832,6381,3212,2639,1107,2904,1434,...,1,1,1,1,1,1,1,1,1,1

In [96]:
lister = []
lister = fucked_up_df.columns.values.tolist()
lister[24242]

'coffers'

In [97]:
final_df = pd.concat([hathi_meta, fucked_up_df], axis=1)

In [103]:
final_df.iloc[:,12]

0       8014
1       2032
2       2441
3        195
4       2836
        ...
3569     NaN
3570     NaN
3571     NaN
3572     NaN
3573     NaN
Name: and, Length: 3574, dtype: object